<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>cn.iocoder.boot</groupId><artifactId>yudao-module-ai-live</artifactId><version>${revision}</version><relativePath>../pom.xml</relativePath></parent><artifactId>yudao-module-ai-live-biz</artifactId><dependencies><dependency><groupId>cn.iocoder.boot</groupId><artifactId>yudao-module-ai-live-api</artifactId><version>${revision}</version></dependency><dependency><groupId>cn.iocoder.boot</groupId><artifactId>yudao-spring-boot-starter-biz-tenant</artifactId></dependency><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-web</artifactId></dependency></dependencies></project>
