<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>cn.iocoder.boot</groupId><artifactId>yudao</artifactId><version>${revision}</version><relativePath>../pom.xml</relativePath></parent><artifactId>yudao-module-ai-live</artifactId><packaging>pom</packaging><modules><module>yudao-module-ai-live-api</module><module>yudao-module-ai-live-biz</module></modules></project>
